"""add store_id to ProductVariant for store isolation

Revision ID: cd60ed470590
Revises: 
Create Date: 2026-08-08 04:39:23.459546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd60ed470590'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_validation')
    op.drop_index(op.f('idx_deal_validation_label'), table_name='deal_validation')
    op.drop_table('deal_validation')
    op.drop_index(op.f('idx_brand_aliases_canonical'), table_name='brand_aliases')
    op.add_column('brands', sa.Column('domain', sa.String(), nullable=False))
    op.add_column('brands', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('brands', sa.Column('region', sa.String(length=2), nullable=True))
    op.add_column('brands', sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True))
    op.add_column('brands', sa.Column('last_successful_sync', sa.DateTime(timezone=True), nullable=True))
    op.add_column('brands', sa.Column('sync_status', sa.String(length=20), nullable=True))
    op.add_column('brands', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('products_count', sa.Integer(), nullable=True))
    op.add_column('brands', sa.Column('reliability_score', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_brands_normalized_name'), table_name='brands', postgresql_where='(normalized_name IS NOT NULL)')
    op.drop_index(op.f('ix_brands_normalized_name'), table_name='brands')
    op.create_index(op.f('ix_brands_normalized_name'), 'brands', ['normalized_name'], unique=True)
    op.create_unique_constraint(None, 'brands', ['domain'])
    op.drop_index(op.f('idx_color_aliases_canonical'), table_name='color_aliases')
    op.alter_column('currency_errors', 'detected_currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=True)
    op.drop_index(op.f('idx_currency_errors_timestamp'), table_name='currency_errors')
    op.alter_column('deal_alerts', 'fingerprint',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('deal_alerts', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deal_alerts', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('deal_alerts', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_deal_alerts_sent_at'), table_name='deal_alerts')
    op.drop_index(op.f('idx_deal_alerts_sku_store_date'), table_name='deal_alerts')
    op.drop_index(op.f('idx_deal_alerts_unique_daily'), table_name='deal_alerts')
    op.create_index('idx_deal_alerts_sku_store_at', 'deal_alerts', ['sku', 'store_id', 'sent_at'], unique=True)
    op.create_unique_constraint(None, 'deal_alerts', ['fingerprint'])
    op.drop_column('deal_alerts', 'sent_date')
    op.alter_column('offers', 'exchange_rate_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_offers_variant'), table_name='offers')
    op.drop_index(op.f('ix_offer_store_variant'), table_name='offers')
    op.drop_index(op.f('uq_offer_store_variant'), table_name='offers')
    op.create_foreign_key(None, 'offers', 'raw_snapshots', ['raw_snapshot_id'], ['id'])
    op.drop_index(op.f('idx_pipeline_runs_started'), table_name='pipeline_runs')
    op.drop_index(op.f('idx_price_changes_variant'), table_name='price_changes')
    op.drop_index(op.f('uq_price_changes_open_interval'), table_name='price_changes', postgresql_where='(ended_at IS NULL)')
    op.drop_constraint(op.f('price_changes_variant_id_fkey'), 'price_changes', type_='foreignkey')
    op.drop_constraint(op.f('price_changes_store_id_fkey'), 'price_changes', type_='foreignkey')
    op.create_foreign_key(None, 'price_changes', 'product_variants', ['variant_id'], ['id'])
    op.create_foreign_key(None, 'price_changes', 'stores', ['store_id'], ['id'])
    op.create_foreign_key(None, 'price_changes', 'raw_snapshots', ['raw_snapshot_id'], ['id'])
    op.create_check_constraint('check_price_change_positive', 'price_changes', 'price > 0')
    op.drop_index(op.f('idx_price_history_variant_time'), table_name='price_history')
    op.alter_column('product_matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('product_matches_canonical_variant_id_matched_variant_id_key'), 'product_matches', type_='unique')
    op.drop_constraint(op.f('chk_confidence'), 'product_matches', type_='check')
    op.add_column('product_variants', sa.Column('store_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_product_variants_gender_age'), table_name='product_variants')
    op.drop_index(op.f('idx_variants_normalized_color'), table_name='product_variants')
    op.drop_index(op.f('idx_variants_normalized_size'), table_name='product_variants')
    op.drop_index(op.f('idx_variants_product_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_pv_external_variant_id'), table_name='product_variants', postgresql_where='(external_variant_id IS NOT NULL)')
    op.create_index(op.f('ix_product_variants_external_product_id'), 'product_variants', ['external_product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_external_variant_id'), 'product_variants', ['external_variant_id'], unique=False)
    op.create_index(op.f('ix_product_variants_normalized_color'), 'product_variants', ['normalized_color'], unique=False)
    op.create_index(op.f('ix_product_variants_normalized_gender_age'), 'product_variants', ['normalized_gender_age'], unique=False)
    op.create_index(op.f('ix_product_variants_normalized_size'), 'product_variants', ['normalized_size'], unique=False)
    op.create_foreign_key(None, 'product_variants', 'stores', ['store_id'], ['id'])
    op.drop_index(op.f('idx_products_brand'), table_name='products')
    op.drop_index(op.f('ix_raw_snapshot_store_time'), table_name='raw_snapshots')
    op.create_index('ix_raw_snapshot_store_time', 'raw_snapshots', ['store_id', 'fetched_at'], unique=False)
    op.add_column('stores', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('stores', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('stores', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('stores', 'currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('stores', 'region',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('stores', 'reliability_score',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_stores_last_sync'), table_name='stores')
    op.drop_index(op.f('idx_stores_reliability'), table_name='stores')
    op.drop_index(op.f('idx_stores_sync_status'), table_name='stores')
    op.drop_index(op.f('uq_stores_domain'), table_name='stores')
    op.create_unique_constraint(None, 'stores', ['domain'])
    op.drop_constraint(op.f('chk_reliability'), 'stores', type_='check')
    op.drop_column('stores', 'last_successful_sync')
    op.drop_column('stores', 'last_sync')
    op.drop_column('stores', 'products_count')
    op.drop_column('stores', 'last_error')
    op.drop_column('stores', 'sync_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('sync_status', sa.VARCHAR(length=20), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('products_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('last_sync', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('last_successful_sync', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_check_constraint(op.f('chk_reliability'), 'stores', 'reliability_score >= 0 AND reliability_score <= 100')
    op.drop_constraint(None, 'stores', type_='unique')
    op.create_index(op.f('uq_stores_domain'), 'stores', ['domain'], unique=True)
    op.create_index(op.f('idx_stores_sync_status'), 'stores', ['sync_status'], unique=False)
    op.create_index(op.f('idx_stores_reliability'), 'stores', [sa.literal_column('reliability_score DESC')], unique=False)
    op.create_index(op.f('idx_stores_last_sync'), 'stores', [sa.literal_column('last_sync DESC')], unique=False)
    op.alter_column('stores', 'reliability_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('stores', 'region',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    op.alter_column('stores', 'currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.drop_column('stores', 'updated_at')
    op.drop_column('stores', 'created_at')
    op.drop_column('stores', 'timezone')
    op.drop_index('ix_raw_snapshot_store_time', table_name='raw_snapshots')
    op.create_index(op.f('ix_raw_snapshot_store_time'), 'raw_snapshots', ['store_id', sa.literal_column('fetched_at DESC')], unique=False)
    op.create_index(op.f('idx_products_brand'), 'products', ['brand_id'], unique=False)
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.drop_index(op.f('ix_product_variants_normalized_size'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_normalized_gender_age'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_normalized_color'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_external_variant_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_external_product_id'), table_name='product_variants')
    op.create_index(op.f('ix_pv_external_variant_id'), 'product_variants', ['external_variant_id'], unique=True, postgresql_where='(external_variant_id IS NOT NULL)')
    op.create_index(op.f('idx_variants_product_sku'), 'product_variants', ['product_id', 'sku'], unique=False)
    op.create_index(op.f('idx_variants_normalized_size'), 'product_variants', ['normalized_size'], unique=False)
    op.create_index(op.f('idx_variants_normalized_color'), 'product_variants', ['normalized_color'], unique=False)
    op.create_index(op.f('idx_product_variants_gender_age'), 'product_variants', ['normalized_gender_age'], unique=False)
    op.drop_column('product_variants', 'store_id')
    op.create_check_constraint(op.f('chk_confidence'), 'product_matches', 'confidence_score >= 0::numeric AND confidence_score <= 1::numeric')
    op.create_unique_constraint(op.f('product_matches_canonical_variant_id_matched_variant_id_key'), 'product_matches', ['canonical_variant_id', 'matched_variant_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('product_matches', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_price_history_variant_time'), 'price_history', ['variant_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_constraint('check_price_change_positive', 'price_changes', type_='check')
    op.drop_constraint(None, 'price_changes', type_='foreignkey')
    op.drop_constraint(None, 'price_changes', type_='foreignkey')
    op.drop_constraint(None, 'price_changes', type_='foreignkey')
    op.create_foreign_key(op.f('price_changes_store_id_fkey'), 'price_changes', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('price_changes_variant_id_fkey'), 'price_changes', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('uq_price_changes_open_interval'), 'price_changes', ['variant_id', 'store_id'], unique=True, postgresql_where='(ended_at IS NULL)')
    op.create_index(op.f('idx_price_changes_variant'), 'price_changes', ['variant_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('idx_pipeline_runs_started'), 'pipeline_runs', [sa.literal_column('started_at DESC')], unique=False)
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_index(op.f('uq_offer_store_variant'), 'offers', ['store_id', 'variant_id'], unique=True)
    op.create_index(op.f('ix_offer_store_variant'), 'offers', ['store_id', 'variant_id'], unique=True)
    op.create_index(op.f('idx_offers_variant'), 'offers', ['variant_id'], unique=False)
    op.alter_column('offers', 'exchange_rate_timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('deal_alerts', sa.Column('sent_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deal_alerts', type_='unique')
    op.drop_index('idx_deal_alerts_sku_store_at', table_name='deal_alerts')
    op.create_index(op.f('idx_deal_alerts_unique_daily'), 'deal_alerts', ['sku', 'store_id', 'sent_date'], unique=True)
    op.create_index(op.f('idx_deal_alerts_sku_store_date'), 'deal_alerts', ['sku', 'store_id', 'sent_date'], unique=True)
    op.create_index(op.f('idx_deal_alerts_sent_at'), 'deal_alerts', [sa.literal_column('sent_at DESC')], unique=False)
    op.alter_column('deal_alerts', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deal_alerts', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('deal_alerts', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deal_alerts', 'fingerprint',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.create_index(op.f('idx_currency_errors_timestamp'), 'currency_errors', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('currency_errors', 'detected_currency',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.create_index(op.f('idx_color_aliases_canonical'), 'color_aliases', ['canonical_id'], unique=False)
    op.drop_constraint(None, 'brands', type_='unique')
    op.drop_index(op.f('ix_brands_normalized_name'), table_name='brands')
    op.create_index(op.f('ix_brands_normalized_name'), 'brands', ['normalized_name'], unique=False)
    op.create_index(op.f('uq_brands_normalized_name'), 'brands', ['normalized_name'], unique=True, postgresql_where='(normalized_name IS NOT NULL)')
    op.drop_column('brands', 'reliability_score')
    op.drop_column('brands', 'products_count')
    op.drop_column('brands', 'last_error')
    op.drop_column('brands', 'sync_status')
    op.drop_column('brands', 'last_successful_sync')
    op.drop_column('brands', 'last_sync')
    op.drop_column('brands', 'region')
    op.drop_column('brands', 'currency')
    op.drop_column('brands', 'domain')
    op.create_index(op.f('idx_brand_aliases_canonical'), 'brand_aliases', ['canonical_id'], unique=False)
    op.create_table('deal_validation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=50), server_default=sa.text("'bogdan'::character varying"), autoincrement=False, nullable=True),
    sa.Column('label', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('validated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['deal_alerts.id'], name=op.f('deal_validation_alert_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deal_validation_pkey')),
    sa.UniqueConstraint('alert_id', 'user_id', name=op.f('deal_validation_alert_id_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_deal_validation_label'), 'deal_validation', ['label'], unique=False)
    op.create_table('match_validation',
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stratum', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_a', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_b', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand_a', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand_b', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('store_a', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('store_b', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url_a', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url_b', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('label', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('size_a', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color_a', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('size_b', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color_b', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price_a', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('price_b', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('match_id', name=op.f('match_validation_pkey'))
    )
    # ### end Alembic commands ###
